from pathlib import Path

from fhir.resources.codesystem import CodeSystem

from oops_fhir.utils import CodeSystemConcept


__all__ = ["DocumentRelationshipType"]

_resource = CodeSystem.parse_file(Path(__file__).with_suffix(".json"))


class DocumentRelationshipType:
    """
    DocumentRelationshipType

    The type of relationship between documents.

    Status: draft - Version: 4.0.1

    Copyright None

    http://hl7.org/fhir/document-relationship-type
    """

    replaces = CodeSystemConcept(
        {
            "code": "replaces",
            "definition": "This document logically replaces or supersedes the target document.",
            "display": "Replaces",
        }
    )
    """
    Replaces

    This document logically replaces or supersedes the target document.
    """

    transforms = CodeSystemConcept(
        {
            "code": "transforms",
            "definition": "This document was generated by transforming the target document (e.g. format or language conversion).",
            "display": "Transforms",
        }
    )
    """
    Transforms

    This document was generated by transforming the target document (e.g. format or language conversion).
    """

    signs = CodeSystemConcept(
        {
            "code": "signs",
            "definition": "This document is a signature of the target document.",
            "display": "Signs",
        }
    )
    """
    Signs

    This document is a signature of the target document.
    """

    appends = CodeSystemConcept(
        {
            "code": "appends",
            "definition": "This document adds additional information to the target document.",
            "display": "Appends",
        }
    )
    """
    Appends

    This document adds additional information to the target document.
    """

    class Meta:
        resource = _resource
