from pathlib import Path

from fhir.resources.codesystem import CodeSystem

from oops_fhir.utils import CodeSystemConcept


__all__ = ["StructureMapTargetListMode"]

_resource = CodeSystem.parse_file(Path(__file__).with_suffix(".json"))


class StructureMapTargetListMode:
    """
    StructureMapTargetListMode

    If field is a list, how to manage the production.

    Status: draft - Version: 4.0.1

    Copyright None

    http://hl7.org/fhir/map-target-list-mode
    """

    first = CodeSystemConcept(
        {
            "code": "first",
            "definition": "when the target list is being assembled, the items for this rule go first. If more than one rule defines a first item (for a given instance of mapping) then this is an error.",
            "display": "First",
        }
    )
    """
    First

    when the target list is being assembled, the items for this rule go first. If more than one rule defines a first item (for a given instance of mapping) then this is an error.
    """

    share = CodeSystemConcept(
        {
            "code": "share",
            "definition": "the target instance is shared with the target instances generated by another rule (up to the first common n items, then create new ones).",
            "display": "Share",
        }
    )
    """
    Share

    the target instance is shared with the target instances generated by another rule (up to the first common n items, then create new ones).
    """

    last = CodeSystemConcept(
        {
            "code": "last",
            "definition": "when the target list is being assembled, the items for this rule go last. If more than one rule defines a last item (for a given instance of mapping) then this is an error.",
            "display": "Last",
        }
    )
    """
    Last

    when the target list is being assembled, the items for this rule go last. If more than one rule defines a last item (for a given instance of mapping) then this is an error.
    """

    collate = CodeSystemConcept(
        {
            "code": "collate",
            "definition": "re-use the first item in the list, and keep adding content to it.",
            "display": "Collate",
        }
    )
    """
    Collate

    re-use the first item in the list, and keep adding content to it.
    """

    class Meta:
        resource = _resource
