from pathlib import Path

from fhir.resources.codesystem import CodeSystem

from oops_fhir.utils import CodeSystemConcept


__all__ = ["v3ObservationCategory"]

_resource = CodeSystem.parse_file(Path(__file__).with_suffix(".json"))


class v3ObservationCategory:
    """
    v3 Code System ObservationCategory

     High level observation categories for the general type of observation
being made. URL: http://hl7-fhir.github.io/valueset-observation-
category.html This is an inline code system
http://hl7.org/fhir/observation-category.

    Status: active - Version: 2018-08-12

    Copyright None

    http://terminology.hl7.org/CodeSystem/v3-ObservationCategory
    """

    exam = CodeSystemConcept(
        {
            "code": "exam",
            "definition": "Observations generated by physical exam findings including direct observations made by a clinician and use of simple instruments and the result of simple maneuvers performed directly on the patient's body.",
            "display": "Exam",
        }
    )
    """
    Exam

    Observations generated by physical exam findings including direct observations made by a clinician and use of simple instruments and the result of simple maneuvers performed directly on the patient's body.
    """

    imaging = CodeSystemConcept(
        {
            "code": "imaging",
            "definition": "Observations generated by imaging. The scope includes observations, plain x-ray, ultrasound, CT, MRI, angiography, echocardiography, nuclear medicine.",
            "display": "Imaging",
        }
    )
    """
    Imaging

    Observations generated by imaging. The scope includes observations, plain x-ray, ultrasound, CT, MRI, angiography, echocardiography, nuclear medicine.
    """

    laboratory = CodeSystemConcept(
        {
            "code": "laboratory",
            "definition": "The results of observations generated by laboratories. Laboratory results are typically generated by laboratories providing analytic services in areas such as chemistry, hematology, serology, histology, cytology, anatomic pathology, microbiology, and/or virology. These observations are based on analysis of specimens obtained from the patient and submitted to the laboratory.",
            "display": "Laboratory",
        }
    )
    """
    Laboratory

    The results of observations generated by laboratories. Laboratory results are typically generated by laboratories providing analytic services in areas such as chemistry, hematology, serology, histology, cytology, anatomic pathology, microbiology, and/or virology. These observations are based on analysis of specimens obtained from the patient and submitted to the laboratory.
    """

    procedure = CodeSystemConcept(
        {
            "code": "procedure",
            "definition": "Observations generated by other procedures. This category includes observations resulting from interventional and non-interventional procedures excluding lab and imaging (e.g. cardiology catheterization, endoscopy, electrodiagnostics, etc.). Procedure results are typically generated by a clinician to provide more granular information about component observations made during a procedure, such as where a gastroenterologist reports the size of a polyp observed during a colonoscopy.",
            "display": "Procedure",
        }
    )
    """
    Procedure

    Observations generated by other procedures. This category includes observations resulting from interventional and non-interventional procedures excluding lab and imaging (e.g. cardiology catheterization, endoscopy, electrodiagnostics, etc.). Procedure results are typically generated by a clinician to provide more granular information about component observations made during a procedure, such as where a gastroenterologist reports the size of a polyp observed during a colonoscopy.
    """

    social_history = CodeSystemConcept(
        {
            "code": "social-history",
            "definition": "The Social History Observations define the patient's occupational, personal (e.g. lifestyle), social, and environmental history and health risk factors, as well as administrative data such as marital status, race, ethnicity and religious affiliation.",
            "display": "Social History",
        }
    )
    """
    Social History

    The Social History Observations define the patient's occupational, personal (e.g. lifestyle), social, and environmental history and health risk factors, as well as administrative data such as marital status, race, ethnicity and religious affiliation.
    """

    survey = CodeSystemConcept(
        {
            "code": "survey",
            "definition": "Assessment tool/survey instrument observations (e.g. Apgar Scores, Montreal Cognitive Assessment (MoCA))",
            "display": "Survey",
        }
    )
    """
    Survey

    Assessment tool/survey instrument observations (e.g. Apgar Scores, Montreal Cognitive Assessment (MoCA))
    """

    therapy = CodeSystemConcept(
        {
            "code": "therapy",
            "definition": "Observations generated by non-interventional treatment protocols (e.g. occupational, physical, radiation, nutritional and medication therapy)",
            "display": "Therapy",
        }
    )
    """
    Therapy

    Observations generated by non-interventional treatment protocols (e.g. occupational, physical, radiation, nutritional and medication therapy)
    """

    vital_signs = CodeSystemConcept(
        {
            "code": "vital-signs",
            "definition": "Clinical observations measure the body's basic functions such as such as blood pressure, heart rate, respiratory rate, height, weight, body mass index, head circumference, pulse oximetry, temperature, and body surface area.",
            "display": "Vital Signs",
        }
    )
    """
    Vital Signs

    Clinical observations measure the body's basic functions such as such as blood pressure, heart rate, respiratory rate, height, weight, body mass index, head circumference, pulse oximetry, temperature, and body surface area.
    """

    class Meta:
        resource = _resource
