from pathlib import Path

from fhir.resources.codesystem import CodeSystem

from oops_fhir.utils import CodeSystemConcept


__all__ = ["v3SetOperator"]

_resource = CodeSystem.parse_file(Path(__file__).with_suffix(".json"))


class v3SetOperator:
    """
    v3 Code System SetOperator

    **** MISSING DEFINITIONS ****

    Status: active - Version: 2018-08-12

    Copyright None

    http://terminology.hl7.org/CodeSystem/v3-SetOperator
    """

    underscore_value_set_operator = CodeSystemConcept(
        {
            "code": "_ValueSetOperator",
            "concept": [
                {
                    "code": "E",
                    "definition": "Form the set-difference with this value, i.e., exclude this element or set from the resulting set.",
                    "display": "exclude",
                },
                {
                    "code": "I",
                    "definition": "Form the union with this value, i.e., include this element or set in the resulting set.",
                    "display": "include",
                },
            ],
            "definition": "Operations that can be used to associate concepts in a terminology.",
            "display": "ValueSetOperator",
            "property": [{"code": "notSelectable", "valueBoolean": True}],
        }
    )
    """
    ValueSetOperator

    Operations that can be used to associate concepts in a terminology.
    """

    a = CodeSystemConcept(
        {
            "code": "A",
            "definition": "Form the intersection with the value.",
            "display": "intersect",
        }
    )
    """
    intersect

    Form the intersection with the value.
    """

    h = CodeSystemConcept(
        {
            "code": "H",
            "definition": "Form the convex hull with the value. The convex hull is defined over ordered domains and is the smallest contiguous superset (interval) that of all the operand sets.",
            "display": "convex hull",
        }
    )
    """
    convex hull

    Form the convex hull with the value. The convex hull is defined over ordered domains and is the smallest contiguous superset (interval) that of all the operand sets.
    """

    p = CodeSystemConcept(
        {
            "code": "P",
            "definition": "Form the periodic hull with the value. The periodic hull is defined over ordered domains and is the periodic set that contains all contiguous supersets of pairs of intervals generated by the operand periodic intervals.",
            "display": "periodic hull",
        }
    )
    """
    periodic hull

    Form the periodic hull with the value. The periodic hull is defined over ordered domains and is the periodic set that contains all contiguous supersets of pairs of intervals generated by the operand periodic intervals.
    """

    class Meta:
        resource = _resource
